<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('rivVoters', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->string('VoterUniqueID');
            $table->string('tsAffNumber');
            $table->string('tszStateVoterID');
            $table->string('longlat');
            $table->string('tsVoterTitle');
            $table->string('tszNameLast');
            $table->string('tszNameFirst');
            $table->string('tszNameMiddle');
            $table->string('tsNameSuffix');
            $table->string('tsGender');
            $table->string('tszSitusAddress');
            $table->string('tszSitusCity');
            $table->string('tsSitusState');
            $table->string('tsSitusZip');
            $table->string('tsHouseNum');
            $table->string('tsUnitAbbr');
            $table->string('tsUnitNum');
            $table->string('tszStreetName');
            $table->string('tsStreetSuffix');
            $table->string('tsPreDir');
            $table->string('tsPostDir');
            $table->string('tszMailAddress1');
            $table->string('tszMailAddress2');
            $table->string('tszMailAddress3');
            $table->string('tszMailAddress4');
            $table->string('tszMailZip');
            $table->string('tszPhone');
            $table->string('tszEmailAddress');
            $table->string('tdtBirthDate');
            $table->string('tsBirthPlace');
            $table->string('tdtRegDate');
            $table->string('tdtOrigRegDate');
            $table->string('tdtLastUpdate_dt');
            $table->string('tsStatusCode');
            $table->string('tszStatusReasonDesc');
            $table->string('tsUserCode1');
            $table->string('tsUserCode2');
            $table->string('tiDuplicateIDFlag');
            $table->string('tszLanguageName');
            $table->string('tszPartyName');
            $table->string('tszAVStatusAbbr');
            $table->string('tszAVStatusDesc');
            $table->string('tszPrecinctName');
            $table->string('tsPrecinctID');
            $table->string('tsPrecinctPortion');
            $table->string('tsDistrictID_0');
            $table->string('tiSubDistrict_0');
            $table->string('tszDistrictName_0');
            $table->string('tsDistrictID_1');
            $table->string('tiSubDistrict_1');
            $table->string('tszDistrictName_1');
            $table->string('tsDistrictID_2');
            $table->string('tiSubDistrict_2');
            $table->string('tszDistrictName_2');
            $table->string('tsDistrictID_3');
            $table->string('tiSubDistrict_3');
            $table->string('tszDistrictName_3');
            $table->string('tsDistrictID_4');
            $table->string('tiSubDistrict_4');
            $table->string('tszDistrictName_4');
            $table->string('tsDistrictID_5');
            $table->string('tiSubDistrict_5');
            $table->string('tszDistrictName_5');
            $table->string('tsElectionAbbr1');
            $table->string('tszElectionDesc1');
            $table->string('tdtElectionDate1');
            $table->string('tsElecTypeDesc1');
            $table->string('tsVotingPrecinct1');
            $table->string('tszVotingMethod1');
            $table->string('tsPartyAbbr1');
            $table->string('tszPartyName1');
            $table->string('tszCountedFlag1');
            $table->string('tszEVSiteDesc1');
            $table->string('tsElectionAbbr2');
            $table->string('tszElectionDesc2');
            $table->string('tdtElectionDate2');
            $table->string('tsElecTypeDesc2');
            $table->string('tsVotingPrecinct2');
            $table->string('tszVotingMethod2');
            $table->string('tsPartyAbbr2');
            $table->string('tszPartyName2');
            $table->string('tszCountedFlag2');
            $table->string('tszEVSiteDesc2');
            $table->string('tsElectionAbbr3');
            $table->string('tszElectionDesc3');
            $table->string('tdtElectionDate3');
            $table->string('tsElecTypeDesc3');
            $table->string('tsVotingPrecinct3');
            $table->string('tszVotingMethod3');
            $table->string('tsPartyAbbr3');
            $table->string('tszPartyName3');
            $table->string('tszCountedFlag3');
            $table->string('tszEVSiteDesc3');
            $table->string('tsElectionAbbr4');
            $table->string('tszElectionDesc4');
            $table->string('tdtElectionDate4');
            $table->string('tsElecTypeDesc4');
            $table->string('tsVotingPrecinct4');
            $table->string('tszVotingMethod4');
            $table->string('tsPartyAbbr4');
            $table->string('tszPartyName4');
            $table->string('tszCountedFlag4');
            $table->string('tszEVSiteDesc4');
            $table->string('tsElectionAbbr5');
            $table->string('tszElectionDesc5');
            $table->string('tdtElectionDate5');
            $table->string('tsElecTypeDesc5');
            $table->string('tsVotingPrecinct5');
            $table->string('tszVotingMethod5');
            $table->string('tsPartyAbbr5');
            $table->string('tszPartyName5');
            $table->string('tszCountedFlag5');
            $table->string('tszEVSiteDesc5');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('rivVoters');
    }
};
