<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('rivVoters', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->string('VoterUniqueID');
            $table->string('tsAffNumber')->nullable();
            $table->string('tszStateVoterID')->nullable();
            $table->string('tsVoterTitle')->nullable();
            $table->string('tszNameLast')->nullable();
            $table->string('tszNameFirst')->nullable();
            $table->string('tszNameMiddle')->nullable();
            $table->string('tsNameSuffix')->nullable();
            $table->string('tsGender')->nullable();
            $table->string('tszSitusAddress')->nullable();
            $table->string('tszSitusCity')->nullable();
            $table->string('tsSitusState')->nullable();
            $table->string('tsSitusZip')->nullable();
            $table->string('tsHouseNum')->nullable();
            $table->string('tsUnitAbbr')->nullable();
            $table->string('tsUnitNum')->nullable();
            $table->string('tszStreetName')->nullable();
            $table->string('tsStreetSuffix')->nullable();
            $table->string('tsPreDir')->nullable();
            $table->string('tsPostDir')->nullable();
            $table->string('tszMailAddress1')->nullable();
            $table->string('tszMailAddress2')->nullable();
            $table->string('tszMailAddress3')->nullable();
            $table->string('tszMailAddress4')->nullable();
            $table->string('tszMailZip')->nullable();
            $table->string('tszPhone')->nullable();
            $table->string('tszEmailAddress')->nullable();
            $table->string('tdtBirthDate')->nullable();
            $table->string('tsBirthPlace')->nullable();
            $table->string('tdtRegDate')->nullable();
            $table->string('tdtOrigRegDate')->nullable();
            $table->string('tdtLastUpdate_dt')->nullable();
            $table->string('tsStatusCode')->nullable();
            $table->string('tszStatusReasonDesc')->nullable();
            $table->string('tsUserCode1')->nullable();
            $table->string('tsUserCode2')->nullable();
            $table->string('tiDuplicateIDFlag')->nullable();
            $table->string('tszLanguageName')->nullable();
            $table->string('tszPartyName')->nullable();
            $table->string('tszAVStatusAbbr')->nullable();
            $table->string('tszAVStatusDesc')->nullable();
            $table->string('tszPrecinctName')->nullable();
            $table->string('tsPrecinctID')->nullable();
            $table->string('tsPrecinctPortion')->nullable();
            $table->string('tsDistrictID_0')->nullable();
            $table->string('tiSubDistrict_0')->nullable();
            $table->string('tszDistrictName_0')->nullable();
            $table->string('tsDistrictID_1')->nullable();
            $table->string('tiSubDistrict_1')->nullable();
            $table->string('tszDistrictName_1')->nullable();
            $table->string('tsDistrictID_2')->nullable();
            $table->string('tiSubDistrict_2')->nullable();
            $table->string('tszDistrictName_2')->nullable();
            $table->string('tsDistrictID_3')->nullable();
            $table->string('tiSubDistrict_3')->nullable();
            $table->string('tszDistrictName_3')->nullable();
            $table->string('tsDistrictID_4')->nullable();
            $table->string('tiSubDistrict_4')->nullable();
            $table->string('tszDistrictName_4')->nullable();
            $table->string('tsDistrictID_5')->nullable();
            $table->string('tiSubDistrict_5')->nullable();
            $table->string('tszDistrictName_5')->nullable();
            $table->string('tsElectionAbbr1')->nullable();
            $table->string('tszElectionDesc1')->nullable();
            $table->string('tdtElectionDate1')->nullable();
            $table->string('tsElecTypeDesc1')->nullable();
            $table->string('tsVotingPrecinct1')->nullable();
            $table->string('tszVotingMethod1')->nullable();
            $table->string('tsPartyAbbr1')->nullable();
            $table->string('tszPartyName1')->nullable();
            $table->string('tszCountedFlag1')->nullable();
            $table->string('tszEVSiteDesc1')->nullable();
            $table->string('tsElectionAbbr2')->nullable();
            $table->string('tszElectionDesc2')->nullable();
            $table->string('tdtElectionDate2')->nullable();
            $table->string('tsElecTypeDesc2')->nullable();
            $table->string('tsVotingPrecinct2')->nullable();
            $table->string('tszVotingMethod2')->nullable();
            $table->string('tsPartyAbbr2')->nullable();
            $table->string('tszPartyName2')->nullable();
            $table->string('tszCountedFlag2')->nullable();
            $table->string('tszEVSiteDesc2')->nullable();
            $table->string('tsElectionAbbr3')->nullable();
            $table->string('tszElectionDesc3')->nullable();
            $table->string('tdtElectionDate3')->nullable();
            $table->string('tsElecTypeDesc3')->nullable();
            $table->string('tsVotingPrecinct3')->nullable();
            $table->string('tszVotingMethod3')->nullable();
            $table->string('tsPartyAbbr3')->nullable();
            $table->string('tszPartyName3')->nullable();
            $table->string('tszCountedFlag3')->nullable();
            $table->string('tszEVSiteDesc3')->nullable();
            $table->string('tsElectionAbbr4')->nullable();
            $table->string('tszElectionDesc4')->nullable();
            $table->string('tdtElectionDate4')->nullable();
            $table->string('tsElecTypeDesc4')->nullable();
            $table->string('tsVotingPrecinct4')->nullable();
            $table->string('tszVotingMethod4')->nullable();
            $table->string('tsPartyAbbr4')->nullable();
            $table->string('tszPartyName4')->nullable();
            $table->string('tszCountedFlag4')->nullable();
            $table->string('tszEVSiteDesc4')->nullable();
            $table->string('tsElectionAbbr5')->nullable();
            $table->string('tszElectionDesc5')->nullable();
            $table->string('tdtElectionDate5')->nullable();
            $table->string('tsElecTypeDesc5')->nullable();
            $table->string('tsVotingPrecinct5')->nullable();
            $table->string('tszVotingMethod5')->nullable();
            $table->string('tsPartyAbbr5')->nullable();
            $table->string('tszPartyName5')->nullable();
            $table->string('tszCountedFlag5')->nullable();
            $table->string('tszEVSiteDesc5')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('rivVoters');
    }
};
